### ISSUE TITLE
How many ws connection on single instance we can hold

### ISSUE THREAD

**Issue by manjeettahkur** [because-why-not/awrtc_signaling#4]
This is my question. Let suppose we have 1 million's user traffic on awrtc_signaling server so how we can scale the server. if we run multiple instances of awrtc_signaling so how web socket handled in that case. Do we need Redis as an extra layer?

**Comment by devluz** [comment]
Ideally, you have an external REST API for such applications that handle tasks like user authentication and the preparation of a call already (e.g. asking the other side if they want to join the call). In this scenario users would only use the signaling server for a few seconds while establishing the final connection and then disconnect from the server again while only keeping the peer to peer connection active. This means the signaling servers have a very low load. Even a cheap VM can likely handle a few hundred users a minute. It is best you do a load test with your specific server & hardware & client requirements though. Make sure to deactivate the verbose log for any load tests. Let us know what you find out.

So far there is no focus on load balancing because this is really only a problem for companies with huge user bases that wouldn't be in the need of our low cost solution in the first place.

**Comment by manjeettahkur** [comment]
I use Thor library for load testing "https://github.com/observing/thor". but Let suppose millions of people connect on the same time so one Instance which is not capable to serve all the request. for that I'm scaling Nodejs server horizontally  I'm trying to scale the code for billions of people. 

What is the best way to scale web socket horizontally which is implemented in your library?



Let suppose is User A connect on EC2 Instance1  and User B connect on EC2 Instance (load-balancer) so how to connect these two users so that they can share the address and after share their address disconnect user A from Instnace 1 and B from Instnace 2.

Currently, I'm trying to save all information into Redis but I think this is not a good approach. I also try pub-sub but it also not working 

I hope you will guide me on this

**Comment by devluz** [comment]
Sorry I missed your comment. I don't think something scaling to billions of users is within the scope of this application. 

As you said just duplicating the process won't work. The load balancing would work better with a REST API that is invoked before. e.g. a common use case would be to have a login first and managing the users friend list. If a user calls another then the REST API can generate a random token + an instance id or custom url for the load balancing. This can then be used by the two to connect. 

Let us know if you found another good way to handle it.

**Comment by manjeettahkur** [comment]
Thank you @devluz  for your response. Well I'm trying rewrite this application taking you code as a source if I'm successful then will let you know
